name: CI
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 conviso-cr:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/flowcli
     env:
       FLOW_API_KEY:  ${{secrets.CONVISO_API_KEY}}
       FLOW_PROJECT_CODE: "ua2w3t-vpFZMVohg"
   steps:
   - uses: actions/checkout@v2

   - name: Run SAST
     run: conviso sast run

   - name: Run SCA
     run: conviso sca run
